### ISSUE TITLE
Unserstanding application of TCBP

### ISSUE THREAD

**Issue by VP-0822** [vivoutlaw/tcbp#1]
I want to integrate TCBP with video captioning task, since in most video captioning tasks with multi-modal inputs at some point different modalities individually encoded and concatenated. I am curious to find out whether the approach discussed in your paper can help jointly understand different modalities? 

> We strongly believe that complete understanding of
video clips can only be achieved by analyzing all modalities
jointly, and hope that such multimodal representations
will inspire the community in the future.

Could you tell me how can your tcbp code snippet be integrated for a task where I have 3 different modalities (Video frame features, audio features, and subtitle/closed captions feature)? Each modality can have different feature dimensions (In my case video has 1024, audio 128 and subtitles 512).

**Comment by vivoutlaw** [comment]
I assume the feature vectors are of dimension: 1024D, 128D and 512D. You can simply concatenate them, resulting in 1664D.
```
from TCBP import TCBP
import torch
data = torch.rand([1,1664,1,1,1])
tcbp = TCBP(input_dim1=1664, input_dim2=1664,output_dim=512, temporal_window=1, spat_x=1, spat_y=1)
tcbp_representation = tcbp(data,data)
tcbp_representation.shape  
>>> torch.Size([1, 512])
```
